### ISSUE TITLE
Gatsby v2

### ISSUE THREAD

**Issue by pierrenel** [kakadiadarpan/gatsby-plugin-sass-resources#1]
Any plans on upgrading your plugin to Gatsby v2?

https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#change-modifywebpackconfig-to-oncreatewebpackconfig

👀

**Comment by kakadiadarpan** [comment]
@pierrenel Thanks for raising this issue. Would you like to try migrating this plugin?

I'm a little occupied with work currently 😅

**Comment by flowen** [comment]
I have no experience with webpack, but with a few pointers I wouldn't mind to give it a try.

(saying: I just tried for an hour without result :/)

**Comment by NandoSangenetto** [comment]
Look like someone did it #2

**Comment by kakadiadarpan** [comment]
Closed with #2

**Comment by kakadiadarpan** [comment]
@pierrenel @flowen @nandosangenetto `gatsby-plugin-sass-resources` v2 is live!

Thanks, @victorcfernandes!
